### ISSUE TITLE
Can't build with OpenImageIO 1.7

### ISSUE THREAD

**Issue by luigino** [GPUOpen-LibrariesAndSDKs/FireRays_SDK#31]
On openSUSE. I know it's not an officially supported platform, but I'll report it nonetheless:

```
/usr/include/OpenImageIO/simd.h: In function 'OpenImageIO::v1_7::simd::mask4 OpenImageIO::v1_7::simd::operator!(const OpenImageIO::v1_7::simd::mask4&)':
/usr/include/OpenImageIO/simd.h:361:42: error: expression cannot be used as a function
         return _mm_xor_ps (a.m_vec, True());
                                          ^
Makefile:202: recipe for target 'obj/x64/Release/main.o' failed
```

**Comment by yozhijk** [comment]
@beasterio , could you investigate?

**Comment by yozhijk** [comment]
Fixed in https://github.com/GPUOpen-LibrariesAndSDKs/FireRays_SDK/commit/f2bb969c5eab63567a3df025d1d97f6c723fdcc2 
Please verify

**Comment by luigino** [comment]
Works now.
Thanks
